# Generated by Django 4.2.1 on 2023-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=250)),
                ('asset_id', models.CharField(max_length=250)),
                ('is_crypto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(max_length=250)),
                ('exchange_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=250)),
                ('period_id', models.CharField(max_length=250)),
            ],
        ),
    ]
